### ISSUE TITLE
R#tableCreate can create the table multiple times thanks to raceconditions

### ISSUE THREAD

**Issue by vladfrangu** [rethinkdb/rethinkdb-ts#4] opened 2018-10-08 17:45 UTC
I have found an annoying quirk with R#tableCreate, where you can run it with the same table name as many times as you want and it will create the table, creating issues due to the table existing multiple times.

This seems to be a race-condition of sorts as it only happens when two processes which are launched at the same time try to create the table if it doesn't exist.

This has never happened before with rethinkdbdash, so I cannot tell why it's happening now... If you need me to do any other debugging, let me know!

**Comment by ronzeidman** [comment] 2018-10-12 15:01
I can't think of a reason this can happen, also I cannot think of a way I can synchronize the requests between two different processes... but even if it's an issue with this driver, the database should probably safe guard against creating two different tables with the same name. In my opinion, this should be an open issue on the main rethinkdb repo.

**Comment by ronzeidman** [comment] 2019-02-08 19:42
Sorry, could not reproduce, closing...

**Closed by ronzeidman** 2019-02-08 19:42 UTC
