### ISSUE TITLE
c.cquery is not a function

### ISSUE THREAD

**Issue by JordanRD** [rethinkdb/rethinkdb-ts#123] opened 2023-09-11 10:31 UTC
please help my i have no idea what happen to my rethink db the error suddenly happen, everything is fine but today when i npm start this error is happening i have no idea how to fix it because i change nothing in my code,

UnhandledPromiseRejectionWarning: TypeError: c.cquery is not a function at Function.run node_modules\rethinkdb-ts\lib\query-builder\query-runner.js:26:36)

**Comment by srh** [comment] 2023-09-11 19:00
Moved to rethinkdb-ts repository.  Maybe there is a bug.

Please make a minimal example reproducing this, and tell us everything about the Node version, NPM version, operating system, and rethinkdb-ts version you're running.

It seems like a strange error -- reading the local code in query-runner.js, the variable `c` must either a RethinkDBConnection or undefined, and RethinkDBConnection has a `query` member function defined.

**Comment by srh** [comment] 2023-09-11 19:10
Wait, I misread. `TypeError: c.cquery` -- what?  `cquery`?  This repo's never had a function named "cquery" or any string of that form, ever:

```
~/sw/rethinkdb-ts$ git log -Scquery
~/sw/rethinkdb-ts$ 
```

**Comment by atassis** [comment] 2023-09-14 10:30
@srh might be right, looks like you have to uninstall `node_modules` and reinstall again, it looks like you accidentally made a change in the library.

**Comment by atassis** [comment] 2023-09-21 13:42
Closing due to unexplained

**Closed by atassis** 2023-09-21 13:42 UTC
