### ISSUE TITLE
ReqlDriverError: query cancelled

### ISSUE THREAD

**Issue by gustavopch** [rethinkdb/rethinkdb-ts#8] opened 2018-11-26 21:52 UTC
When doing `cursor.close()`, the error `ReqlDriverError: query cancelled` gets printed to the console.

```ts
const cursor = await r
  .table('orders')
  .run()

cursor.close()
```

What is the expected way to close a cursor of a changefeed?

**Comment by ronzeidman** [comment] 2018-11-27 18:09
This is the expected way of closing a changefeed, the query cancelled exception is sent to all the cursor listeners by design, you can disable the logging but setting the silent variable to true.

The question is since it's an expected behavior even though it is an exception, should skip logging it. I think you're right and I'll skip logging this specific error, but since it's not critical the fix will be available in the next version.

**Comment by ronzeidman** [comment] 2019-01-24 21:49
try 2.4.0-rc.12

**Closed** 2019-02-08 19:41 UTC
